# Generated by Django 5.0.1 on 2024-01-09 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Polls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('syain_cd', models.IntegerField(blank=True, default=0, null=True, verbose_name='')),
                ('syozoku', models.TextField(blank=True)),
                ('user_name', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=150)),
                ('authority', models.CharField(max_length=150)),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('updated_datetime', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
